name: Build CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup MPI
      run: sudo apt-get install mpich libmpich-dev
    - name: Configure
      run: cd src/; ./configure
    - name: Make
      run: cd src/; make -j
    - name: Drivers
      run: cd src/test/; make all
    - name: Tests
      run: cd src/test/; bash ./runtest.sh TEST_ij/*.sh; bash ./checktest.sh TEST_ij/;
